### ISSUE TITLE
Have you tried apipkg?

### ISSUE THREAD

**Issue by dholth** [njsmith/metamodule#1]
https://pypi.python.org/pypi/apipkg/

**Comment by njsmith** [comment]
Yeah, I'm aware of apipkg -- some guy named 'Daniel Holth' pointed it out
in the python-ideas thread that led to this ;-).

apipkg is really all-or-nothing: you can't really use apipkg for part of
your interface, and standard python conventions for the rest. (In
particular, you run into the problems that arise from copying the module
**dict**, which I described here:
https://mail.python.org/pipermail/python-ideas/2014-October/029786.html).
So if you have a "legacy" package that uses the standard python
conventions, you can't incrementally switch to apipkg without a full
rewrite of your **init**.py. The approach taken by this package is much
more low-impact -- turning it on just gives you the standard python module
definition mechanism + some extra capabilities.

And in any case, really the point of this code is to make an argument for
certain changes to CPython to make these kinds of things easier. apipkg
could benefit from those changes as well :-)

On Thu, Oct 9, 2014 at 2:27 PM, Daniel Holth notifications@github.com
wrote:

> https://pypi.python.org/pypi/apipkg/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/njsmith/metamodule/issues/1.

## 

Nathaniel J. Smith
Postdoctoral researcher - Informatics - University of Edinburgh
http://vorpus.org
