### ISSUE TITLE
Ensure that custom module types have at least a dummy __metamodule_init__

### ISSUE THREAD

**Issue by anntzer** [njsmith/metamodule#2]
Basically the following example fails:

```
from types import ModuleType
import metamodule

class MyModule(ModuleType):
    def __getattr__(self, name):
        return name

metamodule.install(__name__, MyModule)
```

(with `TypeError: 'str' object is not callable`) because metamodule tries to call `MyModule.__metamodule_init__` which triggers `__getattr__` and returns a string.  I guess the options are
1) document it (it's not that bad either, just a bit puzzling)
2) provide a MetamoduleType that subclasses ModuleType with an empty `__metamodule_init__`
3) monkeypatch the type passed as second argument to `metamodule.install` to provide `__metamodule_init__`.

the second option seems the simplest, plus you save a whole import! :-)

**Comment by njsmith** [comment]
Or option (4), just check for `__metamodule_init__` before trying to call it... that seems simplest to me?

Want to make a PR?

**Comment by anntzer** [comment]
If you mean `hasattr(new_module, __metamodule_init__)`, that will still trigger `__getattr__`, which can have various side effects (... e.g. importing).  I decided to just fetch the dunder on the class itself instead.

**Comment by anntzer** [comment]
Any chance you'll make a new release?  Thanks.

**Comment by njsmith** [comment]
thanks for the ping! just uploaded 1.1
